In [1]:
import numpy as np

In [2]:
# Square and Rectangular Matrices
squareMatrix = np.random.randn(5,5)
rectangleMatrix = np.random.randn(5,2)
print(f"SQUARE MATRIX \n\n{squareMatrix}\n\n RECTANGULAR MATRIX\n\n{rectangleMatrix}\n\n")

# Creating Identity matrix
identityMatrix = np.eye(3)
print(f"IDENTITY MATRIX\n\n {identityMatrix}\n\n")

# Creating Zeros matrix
zerosMatrix = np.zeros((4,4))
print(f"ZEROS MATRIX\n\n {zerosMatrix}\n\n")

# Creating Zeros matrix with complex data type
zerosMatrix = np.zeros((4,4), dtype=complex)
print(f"COMPLEX ZEROS MATRIX\n\n {zerosMatrix}\n\n")

# Diagonal Matrix 
diagonalMatrix = np.diag([1,2,3,4,2,1])
print(f"DIAGONAL MATRIX\n\n {diagonalMatrix}\n\n")

# Creating triangular matrix from full matrix 
matFile = np.random.randn(5,5,)
upperTriangularMatrix = np.triu(matFile)
lowerTriangualarMatrix = np.tril(matFile)
print(f"From matrix\n {matFile}\n\n We created upper triangular matrix\n\n {upperTriangularMatrix}\n\n and lower triangular matrix\n\n {lowerTriangualarMatrix}\n\n")

# Concatenate matrices (sizes must match in terms of rows)
matrix1 = np.random.randn(3,2)
matrix2 = np.random.randn(3,4)
concatenatedMatrix = np.concatenate((matrix1,matrix2),axis=1)
print(f"Concatenated matrix of\n\n {matrix1} \n\n and \n\n {matrix2} \n\n is \n\n{concatenatedMatrix}\n\n")

# Matrix transpose - switch rows and columns 
# Symmetric (A=A^T) and skew symmetric (A=-A^T)
symm = np.array([[1, -1, 0],[-1, -2, -4],[0,-4,5]])
skewSymm = np.array([[0, 1, -2],[-1,0,-4],[2,4,0]])
print(f"SYMMETRIC MATRIX\n\n{symm}\n\n SKEW-SYMMETRIC \n\n {skewSymm}")




SQUARE MATRIX 

[[-1.49871314  1.22692814  0.50123672 -0.55372481 -0.10840057]
 [ 1.36624085  1.88166163  0.44738982 -0.69596921  0.20465572]
 [ 0.28788144 -1.05765375 -1.38477614  1.06746531 -0.16728531]
 [ 0.20731322  0.17729805  0.29885825  0.1611919   0.18399716]
 [ 0.16958751 -0.02433325 -0.91098847  0.94931488  2.23554547]]

 RECTANGULAR MATRIX

[[-0.44499196  0.24961248]
 [-0.10293106 -0.57060593]
 [ 2.33313744  0.08691302]
 [-0.9830259   0.30484667]
 [-0.28830034  0.03869195]]


IDENTITY MATRIX

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ZEROS MATRIX

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


COMPLEX ZEROS MATRIX

 [[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


DIAGONAL MATRIX

 [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]]


From matrix
 [[ 0.32815654  0.24687334  0.30890807  0.21089731 -0.94742665]
 [-1.21894327  1.24001538 -1.9510510