In [1]:
import numpy as np

In [2]:
print("""
Rank zero tensors: scalars: x
Rank 1 tensors: vectors: [x1, x2, x3]

                           1     2      3
Rank 2 tensors: matrices: [X1,1  X1,2  X1,3]    1
                          [X2,1  X2,2  X2,3]    2
                          [X3,1  X3,2  X3,3]    3
                          
Matrix/2D tensors/ Rank 2 tensors 

- 2 dimensional array of numbers while vectors are one dimensional array of numbers 
- Denoted in upper case italics while vectors are denoted in lowercase italics 
- Typically, the rows are records of an individual data-point and the columns are the features of a record.
""")
# Square and Rectangular Matrices
squareMatrix = np.random.randn(5,5)
rectangleMatrix = np.random.randn(5,2)
print(f"SQUARE MATRIX \n\n{squareMatrix}\n\n RECTANGULAR MATRIX\n\n{rectangleMatrix}\n\n")

# Creating Identity matrix
identityMatrix = np.eye(3)
print(f"IDENTITY MATRIX\n\n {identityMatrix}\n\n")

# Creating Zeros matrix
zerosMatrix = np.zeros((4,4))
print(f"ZEROS MATRIX\n\n {zerosMatrix}\n\n")

# Creating Zeros matrix with complex data type
zerosMatrix = np.zeros((4,4), dtype=complex)
print(f"COMPLEX ZEROS MATRIX\n\n {zerosMatrix}\n\n")

# Diagonal Matrix 
diagonalMatrix = np.diag([1,2,3,4,2,1])
print(f"DIAGONAL MATRIX\n\n {diagonalMatrix}\n\n")

# Creating triangular matrix from full matrix 
matFile = np.random.randn(5,5,)
upperTriangularMatrix = np.triu(matFile)
lowerTriangualarMatrix = np.tril(matFile)
print(f"From matrix\n {matFile}\n\n We created upper triangular matrix\n\n {upperTriangularMatrix}\n\n and lower triangular matrix\n\n {lowerTriangualarMatrix}\n\n")

# Concatenate matrices (sizes must match in terms of rows)
matrix1 = np.random.randn(3,2)
matrix2 = np.random.randn(3,4)
concatenatedMatrix = np.concatenate((matrix1,matrix2),axis=1)
print(f"Concatenated matrix of\n\n {matrix1} \n\n and \n\n {matrix2} \n\n is \n\n{concatenatedMatrix}\n\n")

# Matrix transpose - switch rows and columns 
# Symmetric (A=A^T) and skew symmetric (A=-A^T)
symm = np.array([[1, -1, 0],[-1, -2, -4],[0,-4,5]])
skewSymm = np.array([[0, 1, -2],[-1,0,-4],[2,4,0]])
print(f"SYMMETRIC MATRIX\n\n{symm}\n\n SKEW-SYMMETRIC \n\n {skewSymm}")





Rank zero tensors: scalars: x
Rank 1 tensors: vectors: [x1, x2, x3]

                           1     2      3
Rank 2 tensors: matrices: [X1,1  X1,2  X1,3]    1
                          [X2,1  X2,2  X2,3]    2
                          [X3,1  X3,2  X3,3]    3
                          
Matrix/2D tensors/ Rank 2 tensors 

- 2 dimensional array of numbers while vectors are one dimensional array of numbers 
- Denoted in upper case italics while vectors are denoted in lowercase italics 
- Typically, the rows are records of an individual data-point and the columns are the features of a record.

SQUARE MATRIX 

[[-0.12921835  0.19873599 -0.35107917 -0.24433108 -0.12361126]
 [-1.30206307  0.137714    1.30958378 -1.29094851 -0.63392107]
 [-0.77421483 -0.15507918  1.02001388  0.87426722 -0.11048122]
 [-0.50296436 -0.96648203 -0.54832022  0.96903789 -0.63792909]
 [-0.8632742   0.67162542 -0.05921289  1.11080835  0.53111596]]

 RECTANGULAR MATRIX

[[ 1.42540163  0.86184976]
 [-0.83693811  0.340

In [27]:
print("""
Tensor Reduction

*Sum of all its elements 
Let’s say the values above are the scores of 5 students in 4 subjects. \nHere, rows represent students(records) and columns represent marks in a subject(features). \nWe can see the sum of scores of each student by summing over the rows. \nWe can see the sum of scores per subject by summing over the columns. \nHere’s how we can do the same.
""")
scores = np.random.randint(1, 100, (5, 4)) # scores range between 1 and 100; 
# we have 5 rows [ students] and 4 columns [ scores/ aka properties]
print(f"5 student scores in four subjects ranging from 1 to 100 represnted in a 2d-tensor. \n- Typically, the rows are records of an individual data-point and the columns are the features of a record. \n\n{scores}\n")
print("Summing over columns/features/Subjects total\n\n")
print(f"{scores.sum(axis=0)}\n\n")
print("**********")
print("Average Score Per Subject\n\n")
print(f"{scores.mean(axis=0)}\n\n")
print("**********")
print("Summing over rows/records/Total per student\n\n")
print(f"{scores.sum(axis=1)}\n\n")
print("**********")
print("Average Score Per Student\n\n")
print(f"{scores.mean(axis=1)}\n\n")
print("**********")
print("""
STANDARD DEVIATION

Standard Deviation is intuitively speaking how bound or spread the distribution of the marks is from the \nmean score of the students. \nIt measures how dispersed the data is from the mean.
""")
print("******************")
print("Spread of average marks in the 4 subjects\n\n")
print(f"{np.std(scores.mean(axis=0))}\n\n")
print("**********")
print("Spread of average marks of students in class\n\n")
print(f"{np.std(scores.mean(axis=1))}\n\n")    
print("**********\n")
print(f"Lowest Score in every subject: \n{scores.min(axis = 0)}\n")
print("**********\n\n")
print(f"Lowest Score secured by each student: \n{scores.min(axis = 1)}\n")
print("**********\n\n")
print(f"Highest Score in every subject: \n{scores.max(axis = 0)}\n")
print("**********\n\n")
print(f"Highest Score secured by each student: \n{scores.max(axis = 1)}\n")
print("**********\n\n")
print("***GLOBAL REDUCTION***\n")
print(f"The global sum of scores is: {scores.sum()}")
print(f"The global sum of scores is: {scores.mean()}")
print(f"The global sum of scores is: {scores.min()}")
print(f"The global sum of scores is: {scores.max()}")

print("""
***************

There are two more reduction operations which in addition to the above ones which are of great significance \nespecially in Machine Learning and Deep Learning.

argmax & argmin

Given an array, it finds out the index of the maximum or minimum element along a given dimension. \nLet us consider using the above example itself. \nSuppose we wanted to find out which student out of the five students scored highest in subject one. \nWe can get the scores for subject one and do an argmax on the same to find this out.

___________________
""")
subject1scores = scores[:, 1]
print(f"Scores: {subject1scores}")
print(f"{subject1scores.argmax()}")
print("""
Since indexing starts at 0, \nwe can see from the scores above that 4th student i.e. \nthe 3rd index is where the scores are highest.

We can find out the same for all the subjects using the entire array and specifying the reduction dimension along the axis. \nSince we want to reduce across the scores, we’ll specify axis = 0
""")
print(f"Student who scored max in each subject: {scores.argmax(axis=0)}\n")
print(f"Student who scored min in each subject: {scores.argmin(axis=0)}\n")

print("""
______________________________________

We can conversely find out which subject did every student performed the best or the worst in by specifying the axis accordingly, we’ll specify axis = 1 for this case and this is how it appears.
""")
print(f"The subject which each of the five students topped in: {scores.argmax(axis=1)}\n")
print(f"The subject which each of the five students struggled in: {scores.argmin(axis=1)}\n")







Tensor Reduction

*Sum of all its elements 
Let’s say the values above are the scores of 5 students in 4 subjects. 
Here, rows represent students(records) and columns represent marks in a subject(features). 
We can see the sum of scores of each student by summing over the rows. 
We can see the sum of scores per subject by summing over the columns. 
Here’s how we can do the same.

5 student scores in four subjects ranging from 1 to 100 represnted in a 2d-tensor. 
- Typically, the rows are records of an individual data-point and the columns are the features of a record. 

[[28 80 22 78]
 [70  8 49 33]
 [66 27 89 85]
 [21 48 38 34]
 [81 77 39 11]]

Summing over columns/features/Subjects total


[266 240 237 241]


**********
Average Score Per Subject


[53.2 48.  47.4 48.2]


**********
Summing over rows/records/Total per student


[208 160 267 141 208]


**********
Average Score Per Student


[52.   40.   66.75 35.25 52.  ]


**********

STANDARD DEVIATION

Standard Deviation is intuiti