In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
print("""
PROBENIUS NORM

- Allows us to quantify the size of a matrix
- Sum of the magnitude of all the vectors in matrix X
""")

x = np.array([[1,2], [3,4]])

#print(proNorm(x))

proNormFunction = np.linalg.norm(x)
print(proNormFunction)



PROBENIUS NORM

- Allows us to quantify the size of a matrix
- Sum of the magnitude of all the vectors in matrix X

5.477225575051661


In [3]:
print("""
MATRIX INVERSION

-This is a clever convinient approach for solving linear equations computationally
- An alternative to manually solving with substitution and elimination
- Matrix inverse of X equals X^-1 whereby X times X^-1 = Identity matrix

regression formula can be summarized as:

y = Xw where y is vector tensor, X is a matrix tensor, and w is a weight tensor of weights a through ....m maybe
y is the outcome, maybe a house price 
X is the predictors, maybe of price
w contains the unknown that models the learnable parameters

Assuming that X^-1 exists, then matrix inversion can solve for w

y = Xw
Xw = y
---------multiplying both sides of the equation by the inverse of the matrix
X^-1.Xw = X^-1.y
Iw = X^-1.y
w = X^-1.y : here lies the solution to vector w

""")

X = np.array([[4,2],[-5,-3]])
xInverse = np.linalg.inv(X)
y = np.array([4,-7])
w = np.dot(xInverse, y) #performs X^-1.y; supports the answer arrived at

print("""

LIMITATIONS TO WHERE WE CAN APPLY MATRIX INVERSION
-Can only be calculated if Matrix isn't singular. 
- i.e all colums of matrix must be linearly independent 
- Square matrix needed
- Overdetermination: the number of rows is greater than the number of columns 
- Underdetermination: the number of rows is less than the number of columns 
""")


MATRIX INVERSION

-This is a clever convinient approach for solving linear equations computationally
- An alternative to manually solving with substitution and elimination
- Matrix inverse of X equals X^-1 whereby X times X^-1 = Identity matrix

regression formula can be summarized as:

y = Xw where y is vector tensor, X is a matrix tensor, and w is a weight tensor of weights a through ....m maybe
y is the outcome, maybe a house price 
X is the predictors, maybe of price
w contains the unknown that models the learnable parameters

Assuming that X^-1 exists, then matrix inversion can solve for w

y = Xw
Xw = y
---------multiplying both sides of the equation by the inverse of the matrix
X^-1.Xw = X^-1.y
Iw = X^-1.y
w = X^-1.y : here lies the solution to vector w




LIMITATIONS TO WHERE WE CAN APPLY MATRIX INVERSION
-Can only be calculated if Matrix isn't singular. 
- i.e all colums of matrix must be linearly independent 
- Square matrix needed
- Overdetermination: the number of rows is

In [4]:
print("""
DIAGONAL MATRICES & ORTHOGONAL MATRICES

-Non-zeroes in diagonal and zeroes everywhere else
- Diagonal matrices are computationally efficient 
- Can be non-square 

ORTHOGONAL MATRICES - made up entirely of orthonormal vectors
- The orthogonal vectors make up all rows and all columns 
- Therefore: A^T.A = AA^T=I where A^T is A transpose
- This means that: A^T = A^-1.I = A^-1
- Calculating A^T is cheap, therefore so is calclating A^-1

""")
diagMatrix = np.array([[1,0,0], [0,1,0], [0,0,1]])
print(f"Diag Matrix: \n{diagMatrix}\n\n")
column_1 = diagMatrix[:,0]
column_2 = diagMatrix[:,1]
column_3 = diagMatrix[:,2]
print(f"Dot products of vectors in matrix above are:\n {np.dot(column_1, column_2)}\n\n {np.dot(column_1, column_3)}\n\n {np.dot(column_2,column_3)}")
print(f"Norm of the vectors in our matrix are: \n {np.linalg.norm(column_1)}\n\n {np.linalg.norm(column_2)}\n\n {np.linalg.norm(column_3)}")
print("\nTherefore, this particular matrix is orthonormal")


DIAGONAL MATRICES & ORTHOGONAL MATRICES

-Non-zeroes in diagonal and zeroes everywhere else
- Diagonal matrices are computationally efficient 
- Can be non-square 

ORTHOGONAL MATRICES - made up entirely of orthonormal vectors
- The orthogonal vectors make up all rows and all columns 
- Therefore: A^T.A = AA^T=I where A^T is A transpose
- This means that: A^T = A^-1.I = A^-1
- Calculating A^T is cheap, therefore so is calclating A^-1


Diag Matrix: 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


Dot products of vectors in matrix above are:
 0

 0

 0
Norm of the vectors in our matrix are: 
 1.0

 1.0

 1.0

Therefore, this particular matrix is orthonormal


In [9]:
ci_eigenvectors_h3 = np.array([[0.996169,0.000000,-0.025615,0.083619],
                               [0.008305,0.707107,0.697680,0.114779],
                               [0.008305,-0.707107,0.697680,0.114779],
                               [-0.086662,0.000000,-0.160717,0.983188]])
ci_eigenvectors_h2 = np.array([[0.000000,-0.185853,-0.350276,0.918022,0.000000,0.000000,0.000000,0.000000],
                              [0.707107,-0.304758,0.614253,0.172673,0.000000,0.000000,0.000000,0.000000],
                              [-0.707107,-0.304758,0.614253,0.172673,0.000000,0.000000,0.000000,0.000000],
                              [0.000000,0.883009,0.350276,0.312414,0.000000,0.000000,0.000000,0.000000],
                              [0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000],
                              [0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000],
                              [0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000],
                              [0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000]])
print(f"{ci_eigenvectors_h3}\n\n{ci_eigenvectors_h2}")
#final_eigenVectors = np.dot(ci_eigenvectors_h3,ci_eigenvectors_h2)

[[ 0.996169  0.       -0.025615  0.083619]
 [ 0.008305  0.707107  0.69768   0.114779]
 [ 0.008305 -0.707107  0.69768   0.114779]
 [-0.086662  0.       -0.160717  0.983188]]

[[ 0.       -0.185853 -0.350276  0.918022  0.        0.        0.
   0.      ]
 [ 0.707107 -0.304758  0.614253  0.172673  0.        0.        0.
   0.      ]
 [-0.707107 -0.304758  0.614253  0.172673  0.        0.        0.
   0.      ]
 [ 0.        0.883009  0.350276  0.312414  0.        0.        0.
   0.      ]
 [ 0.        0.        0.        0.        1.        0.        0.
   0.      ]
 [ 0.        0.        0.        0.        0.        1.        0.
   0.      ]
 [ 0.        0.        0.        0.        0.        0.        1.
   0.      ]
 [ 0.        0.        0.        0.        0.        0.        0.
   1.      ]]
