In [7]:
import numpy as np

# Coefficients of the linear equations
coefficients = np.array([[2, 1, -1, 8],
                        [-3, -1, 2, -11],
                        [-2, 1, 2, -3]], dtype=float)

# printing the initial matrix which is basically set of linear equations x,y,z plus constants
print(f"Initial Matrix:\n {coefficients}")
print("""

""")

# Number of equations and unknowns
num_equations, num_unknowns = coefficients.shape[0], coefficients.shape[1] - 1

# Perform row operations to convert the matrix into row echelon form
for i in range(num_equations):
    if coefficients[i, i] == 0:
        for j in range(i + 1, num_equations):
            if coefficients[j, i] != 0:
                coefficients[[i, j]] = coefficients[[j, i]]
                break

    pivot = coefficients[i, i]
    if pivot != 0:
        coefficients[i] /= pivot

    for j in range(i + 1, num_equations):
        factor = coefficients[j, i]
        coefficients[j] -= factor * coefficients[i]

# Print the row echelon matrix
for equation in coefficients:
    #print(equation[:-1])
    print(equation[:])

Initial Matrix:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]



[ 1.   0.5 -0.5  4. ]
[0. 1. 1. 2.]
[-0. -0.  1. -1.]
